# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: Run_on_Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: dotnet restore
    displayName: 'Restore dependencies'

  - script: dotnet build --configuration Release --no-restore
    displayName: 'Build Blazor project'

  - script: dotnet test
    displayName: 'Run unit tests'

- job: Run_on_Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: dotnet restore
    displayName: 'Restore dependencies'

  - script: dotnet build --configuration Release --no-restore
    displayName: 'Build project on Linux'
