# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: Run on Windows
  pool:
    vmImage: windows-latest

steps:
- script: dotnet test
  displayName: Run unit tests

- job: Run on Linux
pool:
  vmImage: windows-latest

steps:
- scripts: dotnet test
  displayName: Run unit tests

- script: dotnet restore
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Restore dependencies'

- script: dotnet build --configuration Release --no-restore
  displayName: 'Build Blazor project'
